[project]
name = "dl-project" # Modify to use project name
version = "1.0.0"
description = "A multi-platform PyTorch Deep Learning Template"
readme = "README.md"
authors = [
    { name = "Marco Polo Pineda Ortelli", email = "mpineda.ds@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "torch",
    "torchvision",
    "numpy",
    "matplotlib",
    "tqdm",
    "pandas",
    "scikit-learn",
    "torchinfo",
    "seaborn",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/core"]
[[tool.uv.index]]
name = "pytorch-cu"
url = "https://download.pytorch.org/whl/cu132"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu", marker = "sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu", marker = "sys_platform == 'win32'" },
]

[tool.ruff.lint]
# F401 is "unused-import".
# 'unfixable' keeps the warning so you know it's unused, but prevents Ruff from deleting it.
unfixable = ["F401"]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
]
